In [1]:
import pandas as pd

In [25]:
df = pd.read_csv("d:\\works\\AVA\\frame_lists\\train.csv",sep=",", header=None)

In [26]:
df

                                                         0
0           original_vido_id video_id frame_id path labels
1        -5KQ66BBWC4 0 0 -5KQ66BBWC4/-5KQ66BBWC4_000001...
2        -5KQ66BBWC4 0 1 -5KQ66BBWC4/-5KQ66BBWC4_000002...
3        -5KQ66BBWC4 0 2 -5KQ66BBWC4/-5KQ66BBWC4_000003...
4        -5KQ66BBWC4 0 3 -5KQ66BBWC4/-5KQ66BBWC4_000004...
...                                                    ...
6352100  zlVkeKC6Ha8 234 27025 zlVkeKC6Ha8/zlVkeKC6Ha8_...
6352101  zlVkeKC6Ha8 234 27026 zlVkeKC6Ha8/zlVkeKC6Ha8_...
6352102  zlVkeKC6Ha8 234 27027 zlVkeKC6Ha8/zlVkeKC6Ha8_...
6352103  zlVkeKC6Ha8 234 27028 zlVkeKC6Ha8/zlVkeKC6Ha8_...
6352104  zlVkeKC6Ha8 234 27029 zlVkeKC6Ha8/zlVkeKC6Ha8_...

[6352105 rows x 1 columns]

In [24]:
df = pd.read_csv("d:\\works\\AVA\\annotations\\ava_train_v2.1.csv",sep=",", header=None)

FileNotFoundError: [Errno 2] No such file or directory: 'd:\\works\\AVA\\annotations\\ava_train_v2.1.csv'

- video id (0)
- middle_frame_timestamp (1)
  - 타임스탬프(초 단위)
  - 해당 시점의 **중앙 프레임**이 라벨링된 기준
- person_box_x1, y1, x2, y2 : (2~5)
  - 사람 바운딩 박스 좌표
  - **정규화된 값(0~1 사이)** -> 원본 프레임 크기와 무관
- action_id (6)
  - 해당 인물에 라벨링된 행동 클래스 ID
  - AVA V2.2에서는 **80개 액션 클래스** 존재
  - 동일한 bbox에 다른 action_id가 할당됨.
- **person_id** (7) : <br>
  박스 고유 식별자 (이 프레임 내에서 같은 인물을 구분하기 위한 ID)

In [20]:
from IPython.display import display

In [23]:
pd.set_option("display.max_rows", 1000)   # 최대 100행까지 모두 출력
display(df.head(1000))

               0     1      2      3      4      5   6    7
0    -5KQ66BBWC4   902  0.077  0.151  0.283  0.811  80    1
1    -5KQ66BBWC4   902  0.077  0.151  0.283  0.811   9    1
2    -5KQ66BBWC4   902  0.226  0.032  0.366  0.497  12    0
3    -5KQ66BBWC4   902  0.226  0.032  0.366  0.497  17    0
4    -5KQ66BBWC4   902  0.226  0.032  0.366  0.497  80    0
5    -5KQ66BBWC4   902  0.332  0.194  0.481  0.891  80    2
6    -5KQ66BBWC4   902  0.332  0.194  0.481  0.891   9    2
7    -5KQ66BBWC4   902  0.505  0.105  0.653  0.780   9    3
8    -5KQ66BBWC4   902  0.626  0.146  0.805  0.818   9    5
9    -5KQ66BBWC4   902  0.805  0.222  0.997  1.000  80    4
10   -5KQ66BBWC4   902  0.805  0.222  0.997  1.000   9    4
11   -5KQ66BBWC4   903  0.000  0.162  0.177  0.804  80    6
12   -5KQ66BBWC4   903  0.000  0.162  0.177  0.804   9    6
13   -5KQ66BBWC4   903  0.141  0.158  0.298  0.825  12    8
14   -5KQ66BBWC4   903  0.141  0.158  0.298  0.825  80    8
15   -5KQ66BBWC4   903  0.226  0.026  0.363  0.512  12    0
16   -5KQ66BBWC4   903  0.226  0.026  0.363  0.512  80    0
17   -5KQ66BBWC4   903  0.328  0.182  0.484  0.895  80    2
18   -5KQ66BBWC4   903  0.328  0.182  0.484  0.895   9    2
19   -5KQ66BBWC4   903  0.507  0.147  0.666  0.789  80    7
20   -5KQ66BBWC4   903  0.507  0.147  0.666  0.789   9    7
21   -5KQ66BBWC4   903  0.642  0.158  0.791  0.859   9   10
22   -5KQ66BBWC4   903  0.785  0.150  0.886  0.703  12   11
23   -5KQ66BBWC4   903  0.785  0.150  0.886  0.703  80   11
24   -5KQ66BBWC4   903  0.802  0.267  0.994  0.971  80    4
25   -5KQ66BBWC4   903  0.802  0.267  0.994  0.971   9    4
26   -5KQ66BBWC4   903  0.865  0.158  0.991  0.436  80    9
27   -5KQ66BBWC4   903  0.865  0.158  0.991  0.436   9    9
28   -5KQ66BBWC4   904  0.217  0.008  0.982  0.966  12    4
29   -5KQ66BBWC4   904  0.217  0.008  0.982  0.966  80    4
30   -5KQ66BBWC4   905  0.044  0.056  0.236  0.891  12   13
31   -5KQ66BBWC4   905  0.192  0.072  0.411  0.970  12   15
32   -5KQ66BBWC4   905  0.192  0.072  0.411  0.970  80   15
33   -5KQ66BBWC4   905  0.392  0.033  0.556  0.618  14   12
34   -5KQ66BBWC4   905  0.392  0.033  0.556  0.618  17   12
35   -5KQ66BBWC4   905  0.614  0.078  0.826  0.975  12   14
36   -5KQ66BBWC4   905  0.614  0.078  0.826  0.975  80   14
37   -5KQ66BBWC4   906  0.030  0.078  0.225  0.876  12   13
38   -5KQ66BBWC4   906  0.191  0.073  0.399  0.971  12   15
39   -5KQ66BBWC4   906  0.408  0.008  0.586  0.639  14   12
40   -5KQ66BBWC4   906  0.408  0.008  0.586  0.639  17   12
41   -5KQ66BBWC4   906  0.614  0.075  0.821  0.999  12   14
42   -5KQ66BBWC4   906  0.859  0.104  0.996  0.885  12   16
43   -5KQ66BBWC4   907  0.062  0.074  0.234  0.926  12   13
44   -5KQ66BBWC4   907  0.190  0.109  0.396  0.995  12   15
45   -5KQ66BBWC4   907  0.420  0.115  0.616  0.883  14   12
46   -5KQ66BBWC4   907  0.420  0.115  0.616  0.883  17   12
47   -5KQ66BBWC4   907  0.615  0.082  0.823  1.000  12   14
48   -5KQ66BBWC4   908  0.046  0.072  0.340  1.000  12   15
49   -5KQ66BBWC4   908  0.046  0.072  0.340  1.000  80   15
50   -5KQ66BBWC4   908  0.191  0.070  0.320  0.348  12   17
51   -5KQ66BBWC4   908  0.380  0.086  0.693  0.991  14   12
52   -5KQ66BBWC4   908  0.380  0.086  0.693  0.991  17   12
53   -5KQ66BBWC4   908  0.634  0.060  0.919  0.762  12   14
54   -5KQ66BBWC4   909  0.118  0.010  0.889  0.984  12   12
55   -5KQ66BBWC4   909  0.118  0.010  0.889  0.984  17   12
56   -5KQ66BBWC4   909  0.118  0.010  0.889  0.984  79   12
57   -5KQ66BBWC4   909  0.778  0.035  1.000  0.966  12   14
58   -5KQ66BBWC4   910  0.053  0.045  0.824  0.983  12   12
59   -5KQ66BBWC4   910  0.053  0.045  0.824  0.983  17   12
60   -5KQ66BBWC4   910  0.053  0.045  0.824  0.983  79   12
61   -5KQ66BBWC4   911  0.037  0.025  0.826  0.978  12   12
62   -5KQ66BBWC4   911  0.037  0.025  0.826  0.978  17   12
63   -5KQ66BBWC4   911  0.037  0.025  0.826  0.978  79   12
64   -5KQ66BBWC4   912  0.000  0.114  0.602  1.000  12   12
65   -5KQ66BBWC4   912  0.000  0.114  0.602  1.000  74   12
66   -5KQ66BBWC4   912  0.000  0.114  0.602  1.000  80   12
67   -5KQ66BBWC4   912  0.374  0.151  0.874  0.982  12   18
68   -5KQ66BBWC4   912  0.374  0.151  0.874  0.982  79   18
69   -5KQ66BBWC4   912  0.374  0.151  0.874  0.982  80   18
70   -5KQ66BBWC4   913  0.000  0.000  0.282  0.638  12   19
71   -5KQ66BBWC4   913  0.000  0.000  0.282  0.638  74   19
72   -5KQ66BBWC4   913  0.000  0.147  0.564  0.992  12   12
73   -5KQ66BBWC4   913  0.000  0.147  0.564  0.992  74   12
74   -5KQ66BBWC4   913  0.000  0.147  0.564  0.992  80   12
75   -5KQ66BBWC4   913  0.385  0.150  0.883  0.987  12   18
76   -5KQ66BBWC4   913  0.385  0.150  0.883  0.987  79   18
77   -5KQ66BBWC4   913  0.385  0.150  0.883  0.987  80   18
78   -5KQ66BBWC4   914  0.000  0.137  0.600  1.000  12   12
79   -5KQ66BBWC4   914  0.000  0.137  0.600  1.000  74   12
80   -5KQ66BBWC4   914  0.000  0.137  0.600  1.000  79   12
81   -5KQ66BBWC4   914  0.000  0.137  0.600  1.000  80   12
82   -5KQ66BBWC4   914  0.384  0.161  0.882  0.995  12   18
83   -5KQ66BBWC4   914  0.384  0.161  0.882  0.995  79   18
84   -5KQ66BBWC4   914  0.384  0.161  0.882  0.995  80   18
85   -5KQ66BBWC4   915  0.290  0.217  0.680  0.975  12   20
86   -5KQ66BBWC4   915  0.290  0.217  0.680  0.975  17   20
87   -5KQ66BBWC4   915  0.290  0.217  0.680  0.975  79   20
88   -5KQ66BBWC4   915  0.290  0.217  0.680  0.975  80   20
89   -5KQ66BBWC4   915  0.541  0.211  0.657  0.447  12   23
90   -5KQ66BBWC4   915  0.541  0.211  0.657  0.447  74   23
91   -5KQ66BBWC4   915  0.541  0.211  0.657  0.447  80   23
92   -5KQ66BBWC4   915  0.612  0.246  0.811  0.969  12   21
93   -5KQ66BBWC4   915  0.612  0.246  0.811  0.969  74   21
94   -5KQ66BBWC4   915  0.612  0.246  0.811  0.969  80   21
95   -5KQ66BBWC4   915  0.700  0.077  1.000  0.991  12   22
96   -5KQ66BBWC4   915  0.700  0.077  1.000  0.991  74   22
97   -5KQ66BBWC4   916  0.090  0.304  0.296  1.000  12   25
98   -5KQ66BBWC4   916  0.090  0.304  0.296  1.000  74   25
99   -5KQ66BBWC4   916  0.090  0.304  0.296  1.000  80   25
100  -5KQ66BBWC4   916  0.297  0.211  0.666  0.978  12   20
101  -5KQ66BBWC4   916  0.297  0.211  0.666  0.978  17   20
102  -5KQ66BBWC4   916  0.297  0.211  0.666  0.978  79   20
103  -5KQ66BBWC4   916  0.297  0.211  0.666  0.978  80   20
104  -5KQ66BBWC4   916  0.544  0.214  0.661  0.450  12   23
105  -5KQ66BBWC4   916  0.544  0.214  0.661  0.450  74   23
106  -5KQ66BBWC4   916  0.544  0.214  0.661  0.450  80   23
107  -5KQ66BBWC4   916  0.612  0.238  0.816  0.971  12   21
108  -5KQ66BBWC4   916  0.612  0.238  0.816  0.971  74   21
109  -5KQ66BBWC4   916  0.612  0.238  0.816  0.971  80   21
110  -5KQ66BBWC4   916  0.692  0.142  0.998  0.989  12   22
111  -5KQ66BBWC4   916  0.692  0.142  0.998  0.989  74   22
112  -5KQ66BBWC4   916  0.692  0.142  0.998  0.989  80   22
113  -5KQ66BBWC4   916  0.753  0.240  0.858  0.444  12   24
114  -5KQ66BBWC4   916  0.753  0.240  0.858  0.444  74   24
115  -5KQ66BBWC4   916  0.753  0.240  0.858  0.444  80   24
116  -5KQ66BBWC4   917  0.086  0.324  0.293  0.992  12   25
117  -5KQ66BBWC4   917  0.086  0.324  0.293  0.992  74   25
118  -5KQ66BBWC4   917  0.086  0.324  0.293  0.992  80   25
119  -5KQ66BBWC4   917  0.294  0.224  0.684  0.986  12   20
120  -5KQ66BBWC4   917  0.294  0.224  0.684  0.986  17   20
121  -5KQ66BBWC4   917  0.294  0.224  0.684  0.986  79   20
122  -5KQ66BBWC4   917  0.294  0.224  0.684  0.986  80   20
123  -5KQ66BBWC4   917  0.542  0.215  0.659  0.452  12   23
124  -5KQ66BBWC4   917  0.542  0.215  0.659  0.452  74   23
125  -5KQ66BBWC4   917  0.542  0.215  0.659  0.452  80   23
126  -5KQ66BBWC4   917  0.608  0.250  0.811  0.947  12   21
127  -5KQ66BBWC4   917  0.608  0.250  0.811  0.947  74   21
128  -5KQ66BBWC4   917  0.608  0.250  0.811  0.947  80   21
129  -5KQ66BBWC4   917  0.685  0.207  1.000  1.000  12   22
130  -5KQ66BBWC4   917  0.685  0.207  1.000  1.000  74   22
131  -5KQ66BBWC4   917  0.685  0.207  1.000  1.000  80   22
132  -5KQ66BBWC4   917  0.753  0.246  0.857  0.445  12   24
133  -5KQ66BBWC4   917  0.753  0.246  0.857  0.445  74   24
134  -5KQ66BBWC4   917  0.753  0.246  0.857  0.445  80   24
135  -5KQ66BBWC4   918  0.193  0.155  0.735  0.988  12   20
136  -5KQ66BBWC4   918  0.193  0.155  0.735  0.988  17   20
137  -5KQ66BBWC4   918  0.193  0.155  0.735  0.988  79   20
138  -5KQ66BBWC4   918  0.193  0.155  0.735  0.988  80   20
139  -5KQ66BBWC4   918  0.541  0.170  0.700  0.497  12   23
140  -5KQ66BBWC4   918  0.541  0.170  0.700  0.497  74   23
141  -5KQ66BBWC4   918  0.541  0.170  0.700  0.497  80   23
142  -5KQ66BBWC4   918  0.661  0.244  0.904  0.958  12   26
143  -5KQ66BBWC4   918  0.661  0.244  0.904  0.958  74   26
144  -5KQ66BBWC4   918  0.661  0.244  0.904  0.958  80   26
145  -5KQ66BBWC4   918  0.815  0.204  0.971  0.486  12   24
146  -5KQ66BBWC4   918  0.815  0.204  0.971  0.486  80   24
147  -5KQ66BBWC4   919  0.021  0.010  0.834  0.982  12   20
148  -5KQ66BBWC4   919  0.021  0.010  0.834  0.982  17   20
149  -5KQ66BBWC4   919  0.021  0.010  0.834  0.982  79   20
150  -5KQ66BBWC4   919  0.021  0.010  0.834  0.982  80   20
151  -5KQ66BBWC4   920  0.053  0.000  0.861  0.999  12   20
152  -5KQ66BBWC4   920  0.053  0.000  0.861  0.999  79   20
153  -5KQ66BBWC4   921  0.077  0.018  0.930  0.986  12   28
154  -5KQ66BBWC4   922  0.206  0.168  0.805  0.970  17   29
155  -5KQ66BBWC4   922  0.206  0.168  0.805  0.970  64   29
156  -5KQ66BBWC4   922  0.206  0.168  0.805  0.970   9   29
157  -5KQ66BBWC4   923  0.622  0.133  0.807  0.985  64   31
158  -5KQ66BBWC4   923  0.622  0.133  0.807  0.985   9   31
159  -5KQ66BBWC4   925  0.285  0.233  0.541  0.930  17   32
160  -5KQ66BBWC4   925  0.285  0.233  0.541  0.930  64   32
161  -5KQ66BBWC4   925  0.285  0.233  0.541  0.930  80   32
162  -5KQ66BBWC4   925  0.285  0.233  0.541  0.930   9   32
163  -5KQ66BBWC4   925  0.547  0.145  0.848  0.999  59   33
164  -5KQ66BBWC4   925  0.547  0.145  0.848  0.999  64   33
165  -5KQ66BBWC4   925  0.547  0.145  0.848  0.999   9   33
166  -5KQ66BBWC4   926  0.378  0.222  0.887  0.959  64   34
167  -5KQ66BBWC4   926  0.378  0.222  0.887  0.959  80   34
168  -5KQ66BBWC4   926  0.378  0.222  0.887  0.959   9   34
169  -5KQ66BBWC4   929  0.038  0.038  0.970  0.782   8   35
170  -5KQ66BBWC4   930  0.016  0.448  0.722  0.707   8   36
171  -5KQ66BBWC4   930  0.088  0.042  0.940  0.768   8   35
172  -5KQ66BBWC4   931  0.085  0.047  0.966  0.772   8   35
173  -5KQ66BBWC4   932  0.088  0.241  0.253  0.897  12   39
174  -5KQ66BBWC4   932  0.088  0.241  0.253  0.897  80   39
175  -5KQ66BBWC4   932  0.263  0.269  0.603  0.964  64   38
176  -5KQ66BBWC4   932  0.263  0.269  0.603  0.964   9   38
177  -5KQ66BBWC4   932  0.503  0.119  0.947  0.998  64   37
178  -5KQ66BBWC4   932  0.503  0.119  0.947  0.998   9   37
179  -5KQ66BBWC4   933  0.017  0.179  0.184  0.874  12   41
180  -5KQ66BBWC4   933  0.017  0.179  0.184  0.874  80   41
181  -5KQ66BBWC4   933  0.221  0.300  0.677  1.000  64   37
182  -5KQ66BBWC4   933  0.221  0.300  0.677  1.000  80   37
183  -5KQ66BBWC4   933  0.221  0.300  0.677  1.000   9   37
184  -5KQ66BBWC4   933  0.604  0.187  0.766  0.760  12   40
185  -5KQ66BBWC4   933  0.604  0.187  0.766  0.760  80   40
186  -5KQ66BBWC4   934  0.012  0.111  0.344  0.976  12   42
187  -5KQ66BBWC4   934  0.012  0.111  0.344  0.976  64   42
188  -5KQ66BBWC4   934  0.012  0.111  0.344  0.976  80   42
189  -5KQ66BBWC4   934  0.012  0.111  0.344  0.976   9   42
190  -5KQ66BBWC4   934  0.235  0.156  0.334  0.367  12   43
191  -5KQ66BBWC4   934  0.235  0.156  0.334  0.367  80   43
192  -5KQ66BBWC4   934  0.294  0.159  0.464  0.815  12   45
193  -5KQ66BBWC4   934  0.294  0.159  0.464  0.815  80   45
194  -5KQ66BBWC4   934  0.419  0.165  0.537  0.391  12   44
195  -5KQ66BBWC4   934  0.419  0.165  0.537  0.391  80   44
196  -5KQ66BBWC4   935  0.046  0.258  0.332  0.766  64   47
197  -5KQ66BBWC4   935  0.046  0.258  0.332  0.766   9   47
198  -5KQ66BBWC4   935  0.247  0.223  0.382  0.508  12   48
199  -5KQ66BBWC4   935  0.247  0.223  0.382  0.508  80   48
200  -5KQ66BBWC4   935  0.313  0.089  0.866  0.964  64   46
201  -5KQ66BBWC4   935  0.313  0.089  0.866  0.964  80   46
202  -5KQ66BBWC4   935  0.313  0.089  0.866  0.964   9   46
203  -5KQ66BBWC4   935  0.361  0.222  0.478  0.448  12   44
204  -5KQ66BBWC4   935  0.361  0.222  0.478  0.448  80   44
205  -5KQ66BBWC4   935  0.502  0.224  0.647  0.436  12   49
206  -5KQ66BBWC4   935  0.502  0.224  0.647  0.436  80   49
207  -5KQ66BBWC4   936  0.136  0.195  0.304  0.662  12   48
208  -5KQ66BBWC4   936  0.136  0.195  0.304  0.662  80   48
209  -5KQ66BBWC4   936  0.347  0.073  0.792  0.979  64   46
210  -5KQ66BBWC4   936  0.347  0.073  0.792  0.979  80   46
211  -5KQ66BBWC4   936  0.347  0.073  0.792  0.979   9   46
212  -5KQ66BBWC4   938  0.230  0.158  0.494  0.856  64   50
213  -5KQ66BBWC4   938  0.230  0.158  0.494  0.856  80   50
214  -5KQ66BBWC4   938  0.230  0.158  0.494  0.856   9   50
215  -5KQ66BBWC4   939  0.285  0.091  0.770  0.948  64   51
216  -5KQ66BBWC4   939  0.285  0.091  0.770  0.948  80   51
217  -5KQ66BBWC4   939  0.285  0.091  0.770  0.948   9   51
218  -5KQ66BBWC4   941  0.031  0.210  0.671  0.959  64   53
219  -5KQ66BBWC4   941  0.031  0.210  0.671  0.959   9   53
220  -5KQ66BBWC4   941  0.665  0.252  0.996  0.996  80   52
221  -5KQ66BBWC4   941  0.665  0.252  0.996  0.996   9   52
222  -5KQ66BBWC4   942  0.103  0.220  0.726  0.970  64   53
223  -5KQ66BBWC4   942  0.103  0.220  0.726  0.970   9   53
224  -5KQ66BBWC4   942  0.661  0.461  0.997  0.996   1   52
225  -5KQ66BBWC4   942  0.661  0.461  0.997  0.996  64   52
226  -5KQ66BBWC4   944  0.019  0.182  0.462  0.876   5   54
227  -5KQ66BBWC4   944  0.019  0.182  0.462  0.876  64   54
228  -5KQ66BBWC4   944  0.019  0.182  0.462  0.876  80   54
229  -5KQ66BBWC4   945  0.142  0.109  0.562  0.980  64   54
230  -5KQ66BBWC4   945  0.142  0.109  0.562  0.980  80   54
231  -5KQ66BBWC4   945  0.142  0.109  0.562  0.980   9   54
232  -5KQ66BBWC4   946  0.090  0.187  0.313  0.974  64   54
233  -5KQ66BBWC4   946  0.090  0.187  0.313  0.974  80   54
234  -5KQ66BBWC4   946  0.090  0.187  0.313  0.974   9   54
235  -5KQ66BBWC4   947  0.120  0.006  0.337  1.000  64   54
236  -5KQ66BBWC4   947  0.120  0.006  0.337  1.000   9   54
237  -5KQ66BBWC4   947  0.741  0.067  0.889  0.510  12   55
238  -5KQ66BBWC4   947  0.741  0.067  0.889  0.510  80   55
239  -5KQ66BBWC4   947  0.882  0.093  1.000  0.654  12   56
240  -5KQ66BBWC4   947  0.882  0.093  1.000  0.654  80   56
241  -5KQ66BBWC4   948  0.168  0.084  0.419  0.970  64   54
242  -5KQ66BBWC4   948  0.168  0.084  0.419  0.970   9   54
243  -5KQ66BBWC4   948  0.740  0.138  0.892  0.556  12   55
244  -5KQ66BBWC4   948  0.740  0.138  0.892  0.556  80   55
245  -5KQ66BBWC4   948  0.881  0.173  1.000  0.727  12   56
246  -5KQ66BBWC4   948  0.881  0.173  1.000  0.727  80   56
247  -5KQ66BBWC4   949  0.148  0.083  0.456  0.934  64   54
248  -5KQ66BBWC4   949  0.148  0.083  0.456  0.934  80   54
249  -5KQ66BBWC4   949  0.148  0.083  0.456  0.934   9   54
250  -5KQ66BBWC4   949  0.418  0.184  0.523  0.666  12   57
251  -5KQ66BBWC4   949  0.418  0.184  0.523  0.666  80   57
252  -5KQ66BBWC4   949  0.742  0.128  0.890  0.568  12   55
253  -5KQ66BBWC4   949  0.742  0.128  0.890  0.568  80   55
254  -5KQ66BBWC4   949  0.879  0.162  1.000  0.709  12   56
255  -5KQ66BBWC4   949  0.879  0.162  1.000  0.709  80   56
256  -5KQ66BBWC4   950  0.567  0.164  0.729  0.852  12   58
257  -5KQ66BBWC4   950  0.567  0.164  0.729  0.852  80   58
258  -5KQ66BBWC4   951  0.649  0.139  0.886  1.000  64   59
259  -5KQ66BBWC4   951  0.649  0.139  0.886  1.000  80   59
260  -5KQ66BBWC4   951  0.649  0.139  0.886  1.000   9   59
261  -5KQ66BBWC4   951  0.860  0.146  0.980  0.832  12   60
262  -5KQ66BBWC4   951  0.860  0.146  0.980  0.832  80   60
263  -5KQ66BBWC4   952  0.302  0.175  0.542  0.952  64   61
264  -5KQ66BBWC4   952  0.302  0.175  0.542  0.952  80   61
265  -5KQ66BBWC4   952  0.302  0.175  0.542  0.952   9   61
266  -5KQ66BBWC4   952  0.783  0.202  0.894  0.825  12   60
267  -5KQ66BBWC4   952  0.783  0.202  0.894  0.825  80   60
268  -5KQ66BBWC4   952  0.861  0.191  1.000  0.944  12   62
269  -5KQ66BBWC4   952  0.861  0.191  1.000  0.944  80   62
270  -5KQ66BBWC4   953  0.822  0.151  0.993  0.863  12   62
271  -5KQ66BBWC4   953  0.822  0.151  0.993  0.863  80   62
272  -5KQ66BBWC4   954  0.018  0.006  0.365  0.820  64   64
273  -5KQ66BBWC4   954  0.018  0.006  0.365  0.820   9   64
274  -5KQ66BBWC4   954  0.404  0.184  0.659  0.971  64   63
275  -5KQ66BBWC4   954  0.404  0.184  0.659  0.971   9   63
276  -5KQ66BBWC4   954  0.867  0.165  1.000  0.857  12   62
277  -5KQ66BBWC4   954  0.867  0.165  1.000  0.857  80   62
278  -5KQ66BBWC4   955  0.113  0.067  0.587  0.990  64   64
279  -5KQ66BBWC4   955  0.113  0.067  0.587  0.990   9   64
280  -5KQ66BBWC4   956  0.204  0.103  0.814  0.988  64   65
281  -5KQ66BBWC4   956  0.204  0.103  0.814  0.988   9   65
282  -5KQ66BBWC4   957  0.304  0.392  0.755  0.968  64   66
283  -5KQ66BBWC4   957  0.304  0.392  0.755  0.968   9   66
284  -5KQ66BBWC4   958  0.232  0.134  0.349  0.715  12   73
285  -5KQ66BBWC4   958  0.232  0.134  0.349  0.715  80   73
286  -5KQ66BBWC4   958  0.323  0.193  0.460  0.713  12   71
287  -5KQ66BBWC4   958  0.323  0.193  0.460  0.713  80   71
288  -5KQ66BBWC4   958  0.408  0.172  0.512  0.700  12   69
289  -5KQ66BBWC4   958  0.408  0.172  0.512  0.700  80   69
290  -5KQ66BBWC4   958  0.555  0.269  0.918  1.000  64   67
291  -5KQ66BBWC4   958  0.555  0.269  0.918  1.000  80   67
292  -5KQ66BBWC4   958  0.555  0.269  0.918  1.000   9   67
293  -5KQ66BBWC4   958  0.592  0.157  0.691  0.342  12   70
294  -5KQ66BBWC4   958  0.592  0.157  0.691  0.342  80   70
295  -5KQ66BBWC4   958  0.750  0.178  0.860  0.408  12   72
296  -5KQ66BBWC4   958  0.750  0.178  0.860  0.408  80   72
297  -5KQ66BBWC4   958  0.770  0.314  0.941  0.782  64   68
298  -5KQ66BBWC4   958  0.770  0.314  0.941  0.782  80   68
299  -5KQ66BBWC4   958  0.770  0.314  0.941  0.782   9   68
300  -5KQ66BBWC4   959  0.236  0.154  0.336  0.681  12   73
301  -5KQ66BBWC4   959  0.236  0.154  0.336  0.681  80   73
302  -5KQ66BBWC4   959  0.323  0.192  0.455  0.687  12   71
303  -5KQ66BBWC4   959  0.323  0.192  0.455  0.687  80   71
304  -5KQ66BBWC4   959  0.408  0.162  0.491  0.317  12   76
305  -5KQ66BBWC4   959  0.408  0.162  0.491  0.317  80   76
306  -5KQ66BBWC4   959  0.414  0.276  0.743  0.952  64   67
307  -5KQ66BBWC4   959  0.414  0.276  0.743  0.952   9   67
308  -5KQ66BBWC4   959  0.591  0.153  0.704  0.632  12   75
309  -5KQ66BBWC4   959  0.591  0.153  0.704  0.632  80   75
310  -5KQ66BBWC4   959  0.670  0.191  0.784  0.737  12   74
311  -5KQ66BBWC4   959  0.670  0.191  0.784  0.737  17   74
312  -5KQ66BBWC4   959  0.670  0.191  0.784  0.737  80   74
313  -5KQ66BBWC4   959  0.899  0.152  0.996  0.688  12   77
314  -5KQ66BBWC4   959  0.899  0.152  0.996  0.688  80   77
315  -5KQ66BBWC4   960  0.231  0.210  0.591  0.987  64   79
316  -5KQ66BBWC4   960  0.231  0.210  0.591  0.987  80   79
317  -5KQ66BBWC4   960  0.231  0.210  0.591  0.987   9   79
318  -5KQ66BBWC4   960  0.544  0.265  0.935  0.998  64   78
319  -5KQ66BBWC4   960  0.544  0.265  0.935  0.998   9   78
320  -5KQ66BBWC4   960  0.589  0.119  0.701  0.624  12   75
321  -5KQ66BBWC4   960  0.589  0.119  0.701  0.624  80   75
322  -5KQ66BBWC4   961  0.591  0.127  0.708  0.618  12   75
323  -5KQ66BBWC4   961  0.591  0.127  0.708  0.618  80   75
324  -5KQ66BBWC4   961  0.663  0.143  0.803  0.712  12   81
325  -5KQ66BBWC4   961  0.663  0.143  0.803  0.712  80   81
326  -5KQ66BBWC4   961  0.752  0.143  0.856  0.625  12   80
327  -5KQ66BBWC4   961  0.752  0.143  0.856  0.625  80   80
328  -5KQ66BBWC4   962  0.237  0.128  0.348  0.691  12   84
329  -5KQ66BBWC4   962  0.237  0.128  0.348  0.691  80   84
330  -5KQ66BBWC4   962  0.323  0.180  0.463  0.687  12   85
331  -5KQ66BBWC4   962  0.323  0.180  0.463  0.687  80   85

**라벨 ID 매핑**

- AVA dataset은 별도의 **label 파일 (ava_action_list_v2.2.pbtxt)** 로 ID ↔ Action name 매핑이 제공됩니다.

- 예:

    - 1 → bend/bow(굽다/허리를 숙이다) 
    - 12 → "stand"
    - 17 → "talk to"
    - 79 → "listen to person"
    - 80 → work on a commputer (컴퓨터 작업하다)